### ISSUE TITLE
Issue with "fields" on the Market board current data endpoint

### ISSUE THREAD

**Issue by imryano** [Universalis-FFXIV/Universalis#1156]
Hey there,

Just doing some basic tests to try and scope my data calls down to only what I need, but it seems like the "fields" field isn't working as it's suggested it would in the documentation. Here is an example:

![image](https://user-images.githubusercontent.com/9003133/230705439-a3f640af-44cb-4a67-98ea-4349c96ba8cb.png)

This is the exact URL I'm using:
https://universalis.app/api/v2/Materia/36094,36263,4828,27835,36080,36086,36060?listings=3&fields=listings.pricePerUnit

Cheers

**Comment by Feanathiel** [comment]
Seems to be an issue with multiple itemIDs. `items.listings.pricePerUnit` seems to work for that.

**Comment by imryano** [comment]
Totally makes sense. Not an issue with the API then, but might be worth updating the documentation on the field?

**Comment by leiper-mike** [comment]
Seems that if you specify multiple itemIDs it returns a [CurrentlyShownMultiViewV2](https://docs.universalis.app/#schema-currentlyshownmultiviewv2) object instead of the [CurrentlyShownView](https://docs.universalis.app/#schema-currentlyshownview) object that is referenced in the documentation.

**Comment by karashiiro** [comment]
Yes, including multiple item IDs produces a result with the results for each item separated (which therefore has a different structure). I forgot about this issue, will update the docs today.

**Comment by karashiiro** [comment]
Updated, closing this issue
