### ISSUE TITLE
max connections reached: 4000

### ISSUE THREAD

**Issue by ibigfire** [Universalis-FFXIV/Universalis#1274]
I'm getting a "max connections reached: 4000" when trying to use the site.  I'd like to give more information, but that's really all there is to it.  I try to navigate the site and when doing so I just get a message saying "max connections reached: 4000" with nothing else displaying.

**Comment by niZyalB** [comment]
I have the same issue but for me it says "max connections reached: 5000", also no Dalamud price check plugins work anymore they all return 429 too many requests.

**Comment by karashiiro** [comment]
This is due to server load issues, I've been trying to resolve it over the past few days — there's currently no ETA on a fix because there haven't yet been clear signs as to what the underlying problem is, but I'm trying to fix it as quickly as possible.

**Comment by karashiiro** [comment]
Resolved since the start of the month; closing
