### ISSUE TITLE
7.0 items failed loading when language is set to Chinese

### ISSUE THREAD

**Issue by zhyupe** [Universalis-FFXIV/Universalis#1377]
For example, https://universalis.app/market/43685

![image](https://github.com/user-attachments/assets/f5503919-5eab-48b8-9afa-34dfd4b504f4)
![image](https://github.com/user-attachments/assets/a6cf5256-b7ed-42bf-ace0-5481af1a71d4)

**Comment by karashiiro** [comment]
Probably missing game data - deploying an updated version now.

**Comment by karashiiro** [comment]
That did not fix the issue, looking into it

**Comment by karashiiro** [comment]
Fixed, looks like Cafemaker just doesn't have some of those items, yet - updated to fall back to `en` when that happens.
