### ISSUE TITLE
%diff column is virtually useless

### ISSUE THREAD

**Issue by kotarou3** [Universalis-FFXIV/Universalis#1394]
Presently it seems to be "percent difference from the mean asking price", which easily gets dragged around by outliers like people listing items for 99999999 gil

Changing it to use the median asking price (or even median sale price over the last N days) might make it more useful.
Or otherwise, getting rid of the column completely

**Comment by alexcoderabbitai** [comment]
@kotarou3 if you are looking for more accurate statistics that remove outliers. Click the `Saddlebag Exchange` button.  Theres some logic that isolates those sales for more accuracy.

https://saddlebagexchange.com/queries/item-data/4422

**Comment by karashiiro** [comment]
I'll change this to the median sale price over the past 7 days, that sounds like a significantly more useful metric since it tells you what people are actually purchasing at.

**Comment by karashiiro** [comment]
Deployed, let me know what you think!

**Comment by kotarou3** [comment]
Thanks, now it's a lot more useful!

Though perhaps the [mouseover text](https://github.com/Universalis-FFXIV/mogboard-next/blob/09594bb371e40de661bbb9c9a1e176c57056acec/components/SalesTable/SalesTable.tsx#L86-L92) should be updated to say mention "median 7-day sale price"?

**Comment by kotarou3** [comment]
Also, either the value or tooltip has a rounding error? (https://universalis.app/market/42893 on the Elemental market)
![image](https://github.com/user-attachments/assets/e966eb0d-f459-455d-8acd-9088ed9e3a38)

**Comment by karashiiro** [comment]
> Though perhaps the [mouseover text](https://github.com/Universalis-FFXIV/mogboard-next/blob/09594bb371e40de661bbb9c9a1e176c57056acec/components/SalesTable/SalesTable.tsx#L86-L92) should be updated to say mention "median 7-day sale price"?

Good catch, will fix this.

> Also, either the value or tooltip has a rounding error?

Yeah, I intentionally round for the table to avoid clutter, I do think the tooltip should be more precise, though. That `-0%` bugs me too, think this whole bit just needs a small rewrite.

Reopening to track these.

**Comment by karashiiro** [comment]
Deployed the fixes:
![image](https://github.com/user-attachments/assets/b9ef3b0d-ab00-4feb-9e81-a48d990a9349)
