### ISSUE TITLE
Include cheapest 5%, minimum 10 items instead of just the cheapest 10 in market tables

### ISSUE THREAD

**Issue by karashiiro** [Universalis-FFXIV/Universalis#215]
See title. This feature would make it easier to see what items are tending to sell at, which is useful for sellers. The percentage may need to be inversely proportional to the number of items up for sale, so that the page doesn't get absurdly long when there are many items up for sale.

**Comment by Greashun** [comment]
Hi karashiiro, I was wondering if this issue is still open?

**Comment by karashiiro** [comment]
It is still open, yes. It's just a matter of changing the array slice from `10` to something like `min(floor(arr_length*0.05), 10)`, just haven't done it yet.

**Comment by Greashun** [comment]
Just wanted to clarify that the file needed to be altered is within the mogboard folder?

**Comment by karashiiro** [comment]
Yeah, it's just these: https://github.com/Universalis-FFXIV/mogboard/blob/master/templates/Product/item_market_summary.html.twig#L125-L168

**Comment by karashiiro** [comment]
Closed with https://github.com/Universalis-FFXIV/mogboard/commit/b083128e1f05f85a0404d7a7377d7b21aea0e2fe
