### ISSUE TITLE
Localize interface in supported languages

### ISSUE THREAD

**Issue by karashiiro** [Universalis-FFXIV/Universalis#220]
Currently, the language switcher thingy only changes the game data language, not any UI elements. All of the UI text is currently hardcoded, so it'd be a serious pain to switch to a localization (or globalization? I don't know the difference) framework now. Even so, I think it should be done at some point.

**Comment by karashiiro** [comment]
There also seem to be a number of items with untranslated names.

**Comment by BenoitAnastay** [comment]
I think the best way to translate an application is to use gettext, in PHP it does even have a nice underscore alias `_("Hello word")`

[](https://www.php.net/manual/en/function.gettext.php)

Basicly for each strings you put it in a gettext function, you generate the po/mo files and you translate it with your own pace, the files can also be eadily translated by non developpers.
