### ISSUE TITLE
API call ratelimits?

### ISSUE THREAD

**Issue by m4chinations** [Universalis-FFXIV/Universalis#235]
Hi - 

This is just a general question... I'm starting to integrate my application with Universalis' history API - are there any guidelines about API call rate limits? Right now, I tried to set a reasonable limit, I'm calling at most once every 200ms in small bursts, and using the bulk API when possible, I don't want to be flagged as a bot accidentally though.

Love the work that y'all are doing and looking forward to contribute more in the future.

**Comment by karashiiro** [comment]
There's currently no rate limit, and there's been no problems related to that (yet? who knows, but we get a lot of traffic without issue), but you're fine, don't worry ^^ Making bulk requests is helpful enough as it is.

**Comment by m4chinations** [comment]
Thanks! Just making sure 😸
