### ISSUE TITLE
Chinese server support

### ISSUE THREAD

**Issue by karashiiro** [Universalis-FFXIV/Universalis#237]
See #221 as well, I'll repeat some of that here to account for new information.

Now that CN support exists in both TC and Dalamud, it's about time we work on adapting the website to accept and show CN data. One of the biggest challenges was working around XIVAPI not having CN data, but that seems to be solved with [thewakingsands/cafemaker](https://github.com/thewakingsands/cafemaker/wiki).

The current data export tools that need to be run every patch with new marketable items should work the same way with the CN client, but we'd need a CN player to be in charge of that in order to get that data in the first place. We already have developers in Teamcraft who get opcodes, and PR them [here](https://github.com/karashiiro/MachinaWrapperJSON/blob/master/MachinaWrapper/src/Models/Sapphire/Ipcs_cn.cs).

As noted in #220, we'll need to set up an actual localization framework as well. Currently, the core UI is all in English, with the only translated things being whatever XIVAPI or the data exports happen to be provide, and that's quite incomplete. While it is "good enough" in that it provides enough for someone to understand the website, I think we can do better. As noted in the issue by BenoitAnastay, we can just use gettext, I'm not sure how exactly that works with Twig, but it's worth researching.

The character adding stuff, while not totally done for global anyways, also needs to be changed to use ~~whatever CN uses instead of Lodestone~~ just a world and character name, since China does not currently have a Lodestone equivalent.

With all that said, here's a list of what needs to be done to make this happen:

Crucial:
- [x] The backend needs its accepted world range expanded, this should be trivial
- [x] The backend also needs its mapping of world IDs expanded, this should also be trivial
- [x] mogboard's GameDataSource service and cache need to be changed to contextually (or just always in addition?) provide data from cafemaker
- [x] The DataExports tools need to be updated to work with CN installs, they should mostly work out of the box, but some global stuff is hardcoded right now.
- [x] The Redis setup scripts need to be updated to also cache CN DataExports
- [x] CN category files need to be generated and loaded
- [x] Simplified Chinese needs to be added as a selectable language option
- [x] Chinese data centers and worlds need to be selectable
- [x] While the site language is set to Chinese, search results should come from cafemaker

Not crucial, but important:
- [x] Work out gettext and set up proper CN localization
- [ ] Get features like adding characters working

There's also a concern of how much this will increase server load. Currently, CPU usage hovers around 10%, and RAM usage sits at 66% at all times. The RAM usage is concerning, but a 1GB RAM upgrade only costs an additional $5/month on top of the current operating cost. The database currently takes up 29GB, with a maximum size of 80GB, so if it were to hypothetically double in size it would be of no consequence.

**Comment by oott123** [comment]
Hi, we are @thewakingsands (or FFCAFE which is our new name), a group of developers aiming to provide solid support to FFXIV CN players and developers. CafeMaker is made by us, teamcraft opcodes are provided by us too.

We, Chinese players, are excited to see you want to introduce Chinese server support to Universalis!

Please let me know if you need any help on Chinese localization support, we are glad to provide help about that, including translation and in-game data mining. We have a [discord server](https://discord.gg/KYbkUnU) and we can chat there or just on GitHub.

***

There are some details of Chinese servers FYI:

> Chinese (simplified or traditional? I'm not sure how exactly that will work) needs to be added as a selectable language option

Chinese servers, which are running by SHANDA, have Simplified Chinese in-game language only, so we think we should focus on Simplified Chinese for now.

> Get features like adding characters working

We don't have Lodestone for Chinese servers now. Adding characters on Teamcraft just store the character name and world you entered without any verification. Maybe universalis should do something like that.

**Comment by karashiiro** [comment]
Thank you so much! There's currently no localization system set up, but once I get that going I'll reach out to you folks for help with the actual translations. I've also updated the main post to account for what you've noted with regards to the Chinese servers, thanks!

**Comment by karashiiro** [comment]
Unrelated to that, the API should be open for Chinese server data in the next day or two separately from the frontend, for bots or other third-party clients.

**Comment by karashiiro** [comment]
Alright, CN support should be live with #240 following a bunch of bugfixes, let me know if you still get any HTTP 422 errors.

**Comment by karashiiro** [comment]
CN support seems to be fully functional in the API as of #267, third parties should be free to use the data now 🥳 I'll begin frontend work tomorrow.

**Comment by karashiiro** [comment]
The bare minimum frontend work is done, I'll merge this later today and then begin setting up a localization framework.

**Comment by karashiiro** [comment]
Chinese data imports are merged to master, took a little longer because I forgot the category names. It's up on https://universalis.app/ now, just switch the settings 😃

**Comment by karashiiro** [comment]
Ah, I should’ve put this here, too: Translations are now open [here](https://poeditor.com/join/project/yjmqTHXew6), just give me a heads-up when you apply if you don’t use a name I recognize. I’ll make an announcement in the Discord server and elsewhere once I’m done adding all of the strings.
