### ISSUE TITLE
siwtch unapproved item to approved one automatically

### ISSUE THREAD

**Issue by LittleNightmare** [Universalis-FFXIV/Universalis#380]
could unapproved and approved items in the restoration phase share the same data? or reset item id when using API

**Comment by karashiiro** [comment]
Unapproved items can’t be sold on the market board, can they? You need to approve them first anyways.

**Comment by AmenneHolelane** [comment]
correct, unapproved items are untradable

**Comment by LittleNightmare** [comment]
yeah, but players want to know the price of the approved items when they check unapproved items. there are some plugins such as the market board on Dalamud, hold your mouse on the item to get the price.  however, the patches in the Diadem only show unapproved items.

**Comment by karashiiro** [comment]
Oh, I understand now. Sure, I’ll look into this, especially since pmb seems to not get new features anymore.
