### ISSUE TITLE
UX failings

### ISSUE THREAD

**Issue by Arkevorkhat** [Universalis-FFXIV/Universalis#390]
Dear valued developers,

Using the site, I have noticed that, when searching, the results appear in a rather small "pop up"-box.

Indubitably, it is a pretty uncommon way to do this and it would increase usability a lot to extract them into their own page. For inspiration, I may point you to the "giants of the internet".

Following common practices has a lot of benefits to users since they then already know how to use your site!

Thank you very much for considering my proposition. I value your work greatly.

All the best

**Comment by karashiiro** [comment]
Tell that to Vekien; he designed the frontend and lent it out to us. I'll consider it.
