### ISSUE TITLE
Deletion endpoint

### ISSUE THREAD

**Issue by karashiiro** [Universalis-FFXIV/Universalis#433]
I was already working on this, but now I'm making an issue. I'll probably build the functionality into XL first in order to test it and finish it quickly.

**Comment by karashiiro** [comment]
The purchase handler is mostly written already [here](https://github.com/Aireil/Dalamud/commit/d85146c0d9c911634228ee00bd2bf2eed9c8fb52), I just need to add in the actual upload procedure and then test it and fix bugs ad infinitum until this is finished. Will try to do that this week (maybe this weekend?).

**Comment by karashiiro** [comment]
Been busy with school but I can work more on this in a week, starting with finishing off the purchase handler in Dalamud.

**Comment by karashiiro** [comment]
Dalamud stuff PR'd in https://github.com/goatcorp/Dalamud/pull/377

**Comment by karashiiro** [comment]
Opcode scanners were added in https://github.com/karashiiro/FFXIVOpcodes/pull/19 - I'll need to PR DalamudAssets as well to add these (note to self).

**Comment by Aireil** [comment]
I've already added them in DalamudAssets, not sure if they're updated though. I didn't do the latest patches.

**Comment by karashiiro** [comment]
I mostly implemented the draft version of the endpoint a while ago, I just need to work out detecting listing identity. Listing IDs are broke half the time, so I might just do a deep equality check instead.
