### ISSUE TITLE
API rewrite

### ISSUE THREAD

**Issue by karashiiro** [Universalis-FFXIV/Universalis#439]
- [ ] Database migration plan
- [ ] Review of development processes
- [ ] Application architecture review
- [ ] Decide between staying on the same track or doing a small refactor

Who really needs plans, though

**Comment by karashiiro** [comment]
Also see #368, #394, and how long it's taken to finish #433.

**Comment by karashiiro** [comment]
Assuming I do a small refactor, doing it as another learning project is out of the question at this point. That rules out using C/C++ or Rust, and using Postgres.

The options would be C#, TypeScript, Python, or Go for languages, and MongoDB, ArangoDB, or MariaDB for databases. I'm very partial towards C#, but that would require finding a good ORM for it. I'm not a huge fan of EF, especially after trying [ent](https://github.com/ent/ent).

**Comment by karashiiro** [comment]
Something that allows #323 to be automated would be ideal.

**Comment by karashiiro** [comment]
Also see #234 and #208.

**Comment by goaaats** [comment]
> Assuming I do a small refactor, doing it as another learning project is out of the question at this point. That rules out using C/C++ or Rust, and using Postgres.
> 
> The options would be C#, TypeScript, Python, or Go for languages, and MongoDB, ArangoDB, or MariaDB for databases. I'm very partial towards C#, but that would require finding a good ORM for it. I'm not a huge fan of EF, especially after trying [ent](https://github.com/ent/ent).
> 
> If TypeScript was used, I would reuse almost none of the current codebase.

Have you used EF Core? It's pretty straight-forward and one of the better ORMs in my opinion, it's pretty different from old EF though

**Comment by karashiiro** [comment]
I tried EF Core a while ago, I remember that working with schema migrations was a major pain though. I could look into it again.

**Comment by karashiiro** [comment]
It was also two years ago, so there is a good chance I was just being dumb and not realizing it.

**Comment by goaaats** [comment]
Schemas aren't compatible between different databases, but other than that it's just add/remove as usual, been using it for a different project a lot as of late

**Comment by karashiiro** [comment]
C# is sounding like a good option then, maybe
 - EF Core for ORM
 - ASP.NET Core OpenAPI support to make progress on #323 
 - Maybe even put a Discord client in there and do away with the new [alerts](https://github.com/Universalis-FFXIV/alerts) service, and just fire notifications from the API application on accepted uploads
 - The Discord client can just be dropped into the upload route with dependency injection magic
 - MongoDB's C# driver is very easy to use, so I could probably even build the migration into the initial application to ensure that no compatibility issues randomly occur

**Comment by karashiiro** [comment]
And I could use Lumina in there if I need to (maybe for the approved item list and world registration)

**Comment by karashiiro** [comment]
Pinned this and #433, I'll begin working on this after that's closed.

**Comment by karashiiro** [comment]
The new project is fully scaffolded (I think) on the [v2](https://github.com/Universalis-FFXIV/Universalis/tree/v2) branch.

**Comment by karashiiro** [comment]
Splitting this up into two segments: One involving rewriting this without a database change, and another performing that change. That way this can get done sooner, with the new API being a drop-in replacement, and more important features like alerts getting added in sooner.

**Comment by karashiiro** [comment]
The new API has been up for a day without incident; I'll close this and #453 in a few more days if nothing suddenly breaks.

**Comment by karashiiro** [comment]
A thing suddenly broke, fixed with https://github.com/Universalis-FFXIV/Universalis/commit/24b873cd7e3b00cce932e031f0ffac6098cef3e8.

**Comment by karashiiro** [comment]
I still want to do a DB migration eventually in order to unify the frontend and backend databases, and add user data support to the API, but for now I'm considering this done. Will open new issues for these.
