### ISSUE TITLE
Website rewrite

### ISSUE THREAD

**Issue by karashiiro** [Universalis-FFXIV/Universalis#493]
This is not happening anytime soon, but this issue is here to note that it's something I want to do. Quick notes:
- Should be SSR so that requests can be processed within the local network; client-side would both mean that JavaScript would be required to use the website (small con) and that some large responses would need to come from the server, which would eat bandwidth.
- Should be written with some standard JS framework for better potential community support.
- Should ideally be somewhat easily portable to some other framework if/when someone wants to rewrite this again.

**Comment by karashiiro** [comment]
Nevermind, I'm coupling this to #514 and doing it with Razor Pages or something. As more and more mogboard functionality is absorbed into Universalis, more pages will be able to be ported one-by-one to Universalis itself.

**Comment by sciku1** [comment]
I see in #514 is closed now -- is there still a thought to rewrite the frontend?  Might be a good idea to split up the work on a page / feature-by-feature basis.

**Comment by karashiiro** [comment]
Yeah, I have this one under control, though. I've already written interfaces to the mogboard database, so I just need to finish wiring up some API endpoints and then copy/paste templates incrementally.

**Comment by karashiiro** [comment]
[Completed](https://github.com/Universalis-FFXIV/mogboard-next), closing.
