### ISSUE TITLE
Website fails to load

### ISSUE THREAD

**Issue by Siveen** [Universalis-FFXIV/Universalis#551]
Browser: 96.0 (64bit) Win10
Running Kaspersky as Certificate checker
HTTPS connection fails and is considered non-secure, access to the website is not granted.
Accessing the website works just fine via TOR.
Possibly an issue with Kaspersky, can someone verify?
Issue popped up first at New Years.

**Comment by karashiiro** [comment]
Possibly antivirus, for some reason antiviruses have been silently breaking the website for some people. I'd guess it has something to do with them not liking HTTP2, but that's not something I can control (I can't turn that off).

**Comment by Blanckaert** [comment]
It is in Kaspersky, I just excluded Universalis.app IP  and it fixed the issue.  Once I figure out where I did it, I'll repost.

**Comment by Blanckaert** [comment]
Kaspersky - Settings, Network Settings, Trusted addresses, Add, universalis.app, click add, click save, click SAVE again. Might prompt for your password, and ask are you sure to save this change.  <- Make sure you save and say yes or the change will NOT go through.

**Comment by Siveen** [comment]
Can confirm. Cheers. Might wanna contact Kaspersky about it if it is on their end.
