### ISSUE TITLE
Tax rates frozen on Siren on Old Sharlayan

### ISSUE THREAD

**Issue by karashiiro** [Universalis-FFXIV/Universalis#554]
See title. The current data is from XIVLauncher:
```
{ "setName" : "taxRates", "limsaLominsa" : 5, "gridania" : 5, "uldah" : 5, "ishgard" : 3, "kugane" : 0, "crystarium" : 3, "worldID" : 57, "sourceName" : "goat", "oldSharlayan" : 0 }
```

This might be an error in Dalamud parsing (a tax rate of 0 can also suggest failing to read the data) - I'll have to look into it.

**Comment by goaaats** [comment]
![image](https://user-images.githubusercontent.com/16760685/151718315-5afc641a-0e9d-4c6d-8fbc-d8df8aaa4aa5.png)
which one is it, oldsharlayan or sharlayan? I assumed I had it right cuz you told me that you looked at dalamud to implement it

**Comment by karashiiro** [comment]
https://github.com/Universalis-FFXIV/Universalis/blob/v2/src/Universalis.Application/Uploads/Schema/MarketTaxRates.cs

sharlayan, so that should be right.

**Comment by karashiiro** [comment]
I use different keys between the database and the actual upload schema.

**Comment by karashiiro** [comment]
I don't have time right now, but I was going to try and replicate it before bringing it to Dalamud 🥴

**Comment by goaaats** [comment]
fixed on my side
