### ISSUE TITLE
User server settings ignored in web frontend.

### ISSUE THREAD

**Issue by ha-ku** [Universalis-FFXIV/Universalis#574]
I set my server to ChenXiWangZuo in LuXingNiao DC, but the web frontend keep returning data from the Light DC.
![2022-04-13 131611](https://user-images.githubusercontent.com/18721230/163106374-7dba5f51-d126-40dd-8a13-915bb360ce51.png)

**Comment by karashiiro** [comment]
Should be fixed, now.
