### ISSUE TITLE
Slow response time on multiple Ids

### ISSUE THREAD

**Issue by rolandmarg** [Universalis-FFXIV/Universalis#580]
\o

Responses with batch Ids has been slow these two days, is it a known issue? Thanks!

starting request https://universalis.app/api/aether/28591
received response in 0s

starting request https://universalis.app/api/aether/10,11,16,17,12573,27737,27744,28905
received response in 86s

starting request https://universalis.app/api/aether/33657
received response in 1s

starting request https://universalis.app/api/aether/10,12,16,17,18,32947,32948,32953,32954,33869
received response in 121s

**Comment by karashiiro** [comment]
Not known, thanks for the heads-up. I'll look into this later today.

**Comment by karashiiro** [comment]
Looks to be sporadic, testing unique batches at different times only causes this some of the time.

**Comment by karashiiro** [comment]
I rewrote the endpoint to better-utilize the cache, how does this look for you? Seems to work better now, using those queries as tests.

**Comment by rolandmarg** [comment]
hm so it was a cache miss, looks good as of now!
