### ISSUE TITLE
Lists all gone in account

### ISSUE THREAD

**Issue by thekoalaz** [Universalis-FFXIV/Universalis#778]
Hello, somehow my lists have all disappeared from my Universalis account.

Accessing one of them from my browser history seems to work but on the home screen, the left side says "You have no lists".
https://universalis.app/list/c55f7915-7d43-498e-903d-7d9741aa9f29

Let me know if you need any more information.

Thanks!

**Comment by CraftedbyCody** [comment]
Same issue for me as well, all lists, favorites and history are currently missing.

**Comment by karashiiro** [comment]
How recently did you create your accounts? Also, may I have your Discord usernames? I switched the website over to a new auth system yesterday, which may have caused some incompatibility issues.

**Comment by karashiiro** [comment]
Actually, can you show your user IDs? Those can be found here if you refresh the website while signed in:
![Screenshot 2022-07-05 085607](https://user-images.githubusercontent.com/49822414/177372136-6118cfdc-58bb-4c61-8dc7-1d8cbd07ee0b.png)

**Comment by karashiiro** [comment]
Actually, I believe I fixed the problem, can you try checking your lists to see if it worked?

**Comment by thekoalaz** [comment]
Ah, thank you yes! It has been fixed for me. Also, dunno if this is just me, but the loading feels a lot more snappy. :)

Thanks! Feel free to close.
