### ISSUE TITLE
Adding to one list from multiple browser tabs failing

### ISSUE THREAD

**Issue by CraftedbyCody** [Universalis-FFXIV/Universalis#780]
Testing some more and seem to have found another bug. If I open multiple items, such as example: multiple dyes, and then try to add to a list, seems as though only last item added is actually adding. 

Example: 

I opened https://universalis.app/market/8157 and https://universalis.app/market/8161 in new tabs off of my main tab for the website. I clicked lists > clicked on my list "temp favorites" > clicked the x to close list > closed tab. Repeated same process on second tab. With both tabs closed, returned to main tab with all my lists, refreshed, only one of those two items was in the "temp favorites" list, the last one. 

Example video link: https://www.dropbox.com/s/1gu0jyidryr91un/chrome_GxEReDLp7U.mp4?dl=0 

Never had issues doing this before today. 

Browser: Chrome

User: Shandod#4729

**Comment by karashiiro** [comment]
Should be fixed, now.

**Comment by CraftedbyCody** [comment]
Confirmed working on my end, thanks!
