### ISSUE TITLE
Application Error: a client-side exception has occurred

### ISSUE THREAD

**Issue by CraftedbyCody** [Universalis-FFXIV/Universalis#781]
Site really isn't liking me today, hopefully I am not too much of a bother. 

Noticed while testing previously reported multi-tab issue that several times when opening new tabs, I would get the above error (but not always).

Opened console as suggested and found this: 

![image](https://user-images.githubusercontent.com/100868285/177482062-9d48bb81-1a59-40f4-9f59-3f7937e05ca8.png)

**Comment by karashiiro** [comment]
This seems to be caused by the server rate limiting itself; should be fixed now.

It says it's a client-side exception, but it's always preceded by a server-side one as well.

**Comment by karashiiro** [comment]
Working on it
